extern const GeoLayout map_area_1_geo[];
extern const GeoLayout map_area_1[];
extern const Collision map_area_1_collision[];
extern const MacroObject map_area_1_macro_objs[];
extern Lights1 map_dl_f3dlite_material_lights;
extern Lights1 map_dl_f3dlite_material_002_lights;
extern Lights1 map_dl_f3dlite_material_003_lights;
extern Lights1 map_dl_f3dlite_material_004_lights;
extern u8 map_dl_segment2_11C58_rgba16_ci8[];
extern u8 map_dl_segment2_11C58_rgba16_pal_rgba16[];
extern u8 map_dl_wf_textures_05800_rgba16_ci8[];
extern u8 map_dl_wf_textures_05800_rgba16_pal_rgba16[];
extern u8 map_dl_wf_textures_05000_rgba16_ci8[];
extern u8 map_dl_wf_textures_05000_rgba16_pal_rgba16[];
extern u8 map_dl__0_rgba16_rgba16[];
extern u8 map_dl_star_eye_rgba16_ia8[];
extern Vtx map_dl_Plane_mesh_layer_5_vtx_0[29];
extern Gfx map_dl_Plane_mesh_layer_5_tri_0[];
extern Vtx map_dl_Plane_mesh_layer_1_vtx_0[15];
extern Gfx map_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx map_dl_Plane_mesh_layer_1_vtx_1[48];
extern Gfx map_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx map_dl_Plane_mesh_layer_1_vtx_2[27];
extern Gfx map_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx map_dl_Plane_mesh_layer_4_vtx_0[8];
extern Gfx map_dl_Plane_mesh_layer_4_tri_0[];
extern Gfx mat_map_dl_f3dlite_material_001[];
extern Gfx mat_revert_map_dl_f3dlite_material_001[];
extern Gfx mat_map_dl_f3dlite_material[];
extern Gfx mat_revert_map_dl_f3dlite_material[];
extern Gfx mat_map_dl_f3dlite_material_002[];
extern Gfx mat_revert_map_dl_f3dlite_material_002[];
extern Gfx mat_map_dl_f3dlite_material_003[];
extern Gfx mat_map_dl_f3dlite_material_004[];
extern Gfx mat_revert_map_dl_f3dlite_material_004[];
extern Gfx map_dl_Plane_mesh_layer_5[];
extern Gfx map_dl_Plane_mesh_layer_1[];
extern Gfx map_dl_Plane_mesh_layer_4[];
extern Gfx map_dl_material_revert_render_settings[];
